server:
  port: 8888

spring:
  application:
    name: config-server
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        # ?? ??
        native:
          search-locations: file://${user.home}/Desktop/MSA/git-local-repo
#        git:
#          default-label: master # ??? ??
#          uri: file:///Users/choejeong-u/Desktop/MSA/git-local-repo  # ?? ???

          # git
#          uri: https://github.com/chjysm/msa-cloud-config.git
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, bus-refresh

